package com.example.database;

import static com.example.util.Log.start;
import static com.example.util.Log.stop;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import lombok.val;

// probably worth updating to use varargs (...)

/**
 * 
 * Class for database access and manipulation. All methods are static.
 */
public final class Database {

    /**
     * Directory in which the database will be stored.
     */
    private static final String DB_PATH = "./data/database";

    /**
     * URL to access database. H2 is the SQL driver being used.
     */
    private static final String DB_URL = "jdbc:h2:file:" + DB_PATH;

    /**
     * All possible file types generated by database creation.
     */
    private static final String[] DB_EXTENSIONS = new String[] {
            ".mv.db",
            ".trace.db",
            ".lock.db",
    };

    private static final String USER = "sa";
    private static Connection connection;

    private Database() {
    }

    /**
     * Deletes all files in database directory.
     */
    public static void destroyDb() {
        start("destroy db");
        for (val db : DB_EXTENSIONS) {
            val path = DB_PATH + db;
            val file = new File(path);
            if (file.exists()) {
                if (!file.delete()) {
                    throw new RuntimeException(
                            "Failed to delete database file: " + path);
                }
            }
        }
        stop("destroy db");
    }

    /**
     * Destroys existing database, creates new database with tables. Assigns new API
     * for new user.
     * 
     * @param password New user's password to be assigned to database.
     * @param key      New user's massive API key to be stored.
     * @throws SQLException Should connecting to the database or storing the API key
     *                      fail an exception will be thrown.
     */
    public static void newUser(String password, String key)
            throws SQLException {
        start("new user");
        destroyDb();
        login(password);
        createTables();
        newApiKey("massive", key);
        stop("new user");
    }

    /**
     * Creates new connection to database, if non exist a new database will be
     * created.
     * 
     * @param password User password that is used to connect to database.
     * @throws SQLException If connection fails an exception is thrown.
     */
    public static void login(String password) throws SQLException {
        start("login");
        connection = DriverManager.getConnection(DB_URL, USER, password);
        stop("login");
    }

    /**
     * Closes connection to database.
     * 
     * @throws SQLException If closure fails an exception is thrown.
     */
    public static void closeConnection() throws SQLException {
        start("close connection");
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
        stop("close connection");
    }

    /**
     * Checks if database files are present.
     * 
     * @return Whether files are present or not.
     */
    public static boolean dbExists() {
        start("check db exists");
        for (val db : DB_EXTENSIONS) {
            val file = new File(DB_PATH + db);
            if (file.exists()) {
                stop("check db exists");
                return true;
            }
        }
        stop("check db exists");
        return false;
    }

    /**
     * Inserts new API key value. As of now only massive API is used but this method
     * allows to define multiple keys in case of future expansion.
     * 
     * @param name Name of the key to store.
     * @param key  The API key itself.
     * @throws SQLException If insertion fails, an exception is thrown.
     */
    public static void newApiKey(String name, String key) throws SQLException {
        start("new api key");
        insert(Table.API, new String[] { name, key });
        stop("new api key");
    }

    /**
     * Fetches specified API key from database.
     * 
     * @param name Name of the API key to be fetched.
     * @return The API key fetched.
     * @throws SQLException If insertion fails an exception will be thrown.
     */
    public static String getApiKey(String name) throws SQLException {
        start("get api key");
        val result = String.valueOf(selectOne(Table.API, name));
        stop("get api key");
        return result;
    }

    private static enum Table {
        INVENTORY,
        TRANSACTIONS,
        API,
    }

    /**
     * Creates all tables to be used in database.
     * 
     * @throws SQLException If table creation fails an exception will be thrown.
     */
    private static void createTables() throws SQLException {
        start("create tables");
        String sql = Query.createTables();
        try (val statement = connection.createStatement()) {
            statement.execute(sql);
            connection.commit();
        }
        stop("create tables");
    }

    /**
     * Inserts values into specified table.
     * 
     * @param table  The table to insert values into.
     * @param values The values to be inserted.
     * @throws SQLException If insertion fails an exception will be thrown.
     */
    private static void insert(Table table, Object[] values)
            throws SQLException {
        start("insert row");
        String query = switch (table) {
            case TRANSACTIONS -> Query.insetIntoTrans(values);
            case API -> Query.insertIntoApi(values);
            case INVENTORY -> Query.insetIntoTrans(values);
        };

        try (val statement = connection.createStatement()) {
            statement.execute(query);
            connection.commit();
        }
        stop("insert row");
    }

    /**
     * Selects one value from a table and returns it as an {@link Object}.
     * 
     * @param table  The table to select from.
     * @param target The related field to target the selection value.
     * @return The selected value as an {@link Object}.
     * @throws SQLException If selection fails an exception will be thrown.
     */
    private static Object selectOne(Table table, String target)
            throws SQLException {
        start("select record");
        String sql = switch (table) {
            case API -> Query.selectFromApi(target);
            default -> "";
        };

        try (
                val statement = connection.prepareStatement(sql);
                ResultSet results = statement.executeQuery()) {
            if (results.next()) {
                stop("select record");
                return results.getObject(1);
            } else {
                throw new SQLException("no objects found in table");
            }
        }
    }

    /**
     * Selects all values in a table and returns as array of {@link Object}s.
     * 
     * @param table The table to select from.
     * @return An array of values from selection.
     * @throws SQLException If selection fails an exception will be thrown.
     */
    private static Object[] selectAll(Table table) throws SQLException {
        start("select all");
        String sql;

        if (table == Table.TRANSACTIONS) {
            sql = Query.selectAllFromTrans();
        } else if (table == Table.INVENTORY) {
            sql = Query.selectAllFromInvent();
        } else {
            throw new IllegalArgumentException("Invalid table for select all");
        }

        val results = new ArrayList<String>();

        try (
                val statement = connection.prepareStatement(sql);
                ResultSet result = statement.executeQuery()) {
            while (result.next()) {
                val rowString = new StringBuilder();
                val meta = result.getMetaData();

                for (int i = 1; i <= meta.getColumnCount(); i++) {
                    if (i > 1) {
                        rowString.append(',');
                    }
                    rowString.append(result.getObject(i));
                }
                results.add(String.valueOf(rowString));
            }
        }

        stop("select all");
        return results.toArray(new String[0]);
    }
}
