CREATE TABLE IF NOT EXISTS users (
    password NVARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code NVARCHAR(5) NOT NULL,
    exchange NVARCHAR(12) NOT NULL,
    quantity DOUBLE NOT NULL,
    UNIQUE(code)
);

CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code NVARCHAR(5) NOT NULL,
    exchange NVARCHAR(12) NOT NULL,
    quantity DOUBLE NOT NULL,
    price DOUBLE NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    buy BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
    name NVARCHAR(12) NOT NULL PRIMARY KEY,
    api_key NVARCHAR(25) NOT NULL
);
